# Generated by Django 4.2.1 on 2023-05-11 13:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrawnFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(max_length=50)),
                ('feature', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
