# Generated by Django 4.2.1 on 2023-05-18 01:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_drawnfeature_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_app.user')),
            ],
        ),
    ]
